spring:
  application:
    name: dm-gateway-zuul
server:
  port: 7600
zuu===
  routes: dm-user-consumer:/user/**
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/